### PR TITLE
Create test1-d.output.txt

### PR DESCRIPTION
**Pull request by Akshay199456**
These are the results that I obtained. This is by no means the right answer. This is only meant to serve as a guide till the TA posts the results or the right answers to the test cases.

### CODE REVIEW

**Comment by aleman** [comment]
The file looked good, not sure why you closed the pull-request.

**Comment by Akshay199456** [comment]
Hi Prof,

I will be creating a pull request of the possible solutions to the test
cases by tomorrow if the TAs don't post the solutions or complete grading
it.

Regards
Akshay Mysore

**Comment by Akshay199456** [comment]
Hi Prof,

Sorry for the long list of emails that you will receive for the pull
requests. I initially thought to create a pull request for each test case
but then decided to just create one for all the test cases ( It would just
be more useful to have all of them at one location in addition to it being
more easier for you to just accept one). I have closed the other pull
requests as required.

Your Sincerely
Akshay Kumar

**Comment by aleman** [comment]
No problem. 
There's a way to do one pull request for all files as one set.
I'd rather not explain it in the wrong way though. I'll see if I find a good example elsewhere.

**Pull request closed without merging**
